steps:
  - group: ":julia: CUDA GPU"
    steps:
      - label: ":julia: Julia {{matrix.julia}} + CUDA GPU"
        plugins:
          - JuliaCI/julia#v1:
              version: "{{matrix.julia}}"
          - JuliaCI/julia-test#v1:
              test_args: "--quickfail"
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
                - ext
        agents:
          queue: "juliagpu"
          cuda: "*"
        env:
          BACKEND_GROUP: "CUDA"
        if: build.message !~ /\[skip tests\]/
        timeout_in_minutes: 240
        matrix:
          setup:
            julia:
              - "1"

  # Downstream CUDA Tests
  - group: ":telescope: Downstream CUDA"
    steps:
      - label: ":julia: {{matrix.repo}} (Julia {{matrix.julia}} + CUDA GPU)"
        plugins:
          - JuliaCI/julia#v1:
              version: "{{matrix.julia}}"
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
        command: |
          julia --code-coverage=user --color=yes --project -e '
            using Pkg

            repo = ENV["DOWNSTREAM_TEST_REPO"]

            println("--- :julia: Instantiating project")
            withenv("JULIA_PKG_PRECOMPILE_AUTO" => 0) do
              Pkg.instantiate()

              try
                Pkg.develop(repo)
                println("+++ :julia: Running tests")
                Pkg.test("$(repo)"; coverage=true)
              catch err
                err isa Pkg.Resolve.ResolverError || rethrow()
                @info "Not compatible with this release. No problem." exception=err
                exit(0)
              end
            end

            println("+++ :julia: Finished Downstream Test")'
        agents:
          queue: "juliagpu"
          cuda: "*"
        env:
          BACKEND_GROUP: "CUDA"
          DOWNSTREAM_TEST_REPO: "{{matrix.repo}}"
        if: build.message !~ /\[skip tests\]/ || build.message !~ /\[skip downstream\]/
        timeout_in_minutes: 240
        matrix:
          setup:
            julia:
              - "1"
            repo:
              - "Lux"
              - "Boltz"

  - group: ":julia: AMD GPU"
    steps:
      - label: ":julia: Julia: {{matrix.julia}} + AMD GPU"
        plugins:
          - JuliaCI/julia#v1:
              version: "{{matrix.julia}}"
          - JuliaCI/julia-test#v1:
              test_args: "--quickfail"
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
                - ext
        env:
          JULIA_AMDGPU_CORE_MUST_LOAD: "1"
          JULIA_AMDGPU_HIP_MUST_LOAD: "1"
          JULIA_AMDGPU_DISABLE_ARTIFACTS: "1"
          BACKEND_GROUP: "AMDGPU"
        agents:
          queue: "juliagpu"
          rocm: "*"
          rocmgpu: "*"
        if: build.message !~ /\[skip tests\]/
        timeout_in_minutes: 60
        matrix:
          setup:
            julia:
              - "1"

  # Downstream AMDGPU Tests
  - group: ":telescope: Downstream AMD GPU"
    steps:
      - label: ":julia: {{matrix.repo}} (Julia {{matrix.julia}} + AMD GPU)"
        plugins:
          - JuliaCI/julia#v1:
              version: "{{matrix.julia}}"
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
        command: |
          julia --code-coverage=user --color=yes --project -e '
            using Pkg

            repo = ENV["DOWNSTREAM_TEST_REPO"]

            println("--- :julia: Instantiating project")
            withenv("JULIA_PKG_PRECOMPILE_AUTO" => 0) do
              Pkg.instantiate()

              try
                Pkg.develop(repo)
                println("+++ :julia: Running tests")
                Pkg.test("$(repo)"; coverage=true)
              catch err
                err isa Pkg.Resolve.ResolverError || rethrow()
                @info "Not compatible with this release. No problem." exception=err
                exit(0)
              end
            end

            println("+++ :julia: Finished Downstream Test")'
        agents:
          queue: "juliagpu"
          rocm: "*"
          rocmgpu: "*"
        env:
          BACKEND_GROUP: "AMDGPU"
          JULIA_AMDGPU_CORE_MUST_LOAD: "1"
          JULIA_AMDGPU_HIP_MUST_LOAD: "1"
          JULIA_AMDGPU_DISABLE_ARTIFACTS: "1"
          DOWNSTREAM_TEST_REPO: "{{matrix.repo}}"
        if: build.message !~ /\[skip tests\]/ || build.message !~ /\[skip downstream\]/
        timeout_in_minutes: 240
        matrix:
          setup:
            julia:
              - "1"
            repo:
              - "Lux"
              - "Boltz"

  - group: ":julia: Metal GPU"
    steps:
      - label: ":julia: Julia: {{matrix.julia}} + Metal"
        plugins:
          - JuliaCI/julia#v1:
              version: "{{matrix.julia}}"
          - JuliaCI/julia-test#v1:
              test_args: "--quickfail"
          # - JuliaCI/julia-coverage#v1:
          #     codecov: true
          #     dirs:
          #       - src
          #       - ext
        agents:
          queue: "juliaecosystem"
          os: "macos"
          arch: "aarch64"
        env:
          BACKEND_GROUP: "Metal"
        if: build.message !~ /\[skip tests\]/
        timeout_in_minutes: 60
        matrix:
          setup:
            julia:
              - "1"

  - group: ":julia: oneAPI GPU"
    steps:
      - label: ":julia: Julia: {{matrix.julia}} + oneAPI"
        plugins:
          - JuliaCI/julia#v1:
              version: "{{matrix.julia}}"
          - JuliaCI/julia-test#v1:
              test_args: "--quickfail"
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
                - ext
        env:
          BACKEND_GROUP: "oneAPI"
        agents:
          queue: "juliagpu"
          intel: "*"
        if: build.message !~ /\[skip tests\]/
        timeout_in_minutes: 60
        matrix:
          setup:
            julia:
              - "1"

env:
  RETESTITEMS_NWORKERS: 8
  RETESTITEMS_NWORKER_THREADS: 2
  SECRET_CODECOV_TOKEN: "DpNKbuKYRX40vpyJCfTvQmxwls1hlCUWiZX4pnsukt9E8u4pf0WUcIroRv2UDDbGYjuk5izmZ9yAhZZhiGMhjFF/TIji3JiYe1sXWdfSrNk0N2+CNoXo+CIi3JvS7mB+YAIUTEi2Xph+L7R0d+It079PEispqVv4bdRuqgSbY7Rn3NSsoV1cB8uUaVFBJH4EewC6Hceg80QW7q+CBru+QECudKbAWnRVLoizRsgzIld+gTUqsI1PhR+vSpD+AfZzhVxmff55ttVcMUFGnL3w4L74qoLVPET52/GPLCOi3RLGSzBJjebSBqqKOwesT9xJ4yaZ21AEzyeOm86YRc2WYg==;U2FsdGVkX1/eBwyJ7Of++vKyAWDSBvSdJeiKmVmlaVKFU5CHejM+sDlSZWH/WmoBatLcqH+eUVEGXC+oWl5riw=="
